# Generated by Django 5.2.14 on 2026-05-12 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_adminprofile_rename_officer_officerprofile_and_more'),
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictDashboardProjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('pending_count', models.IntegerField(default=0)),
                ('assigned_count', models.IntegerField(default=0)),
                ('resolved_count', models.IntegerField(default=0)),
                ('high_priority_count', models.IntegerField(default=0)),
                ('last_event_id', models.IntegerField(default=0, help_text='Last processed event ID for idempotency')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department')),
            ],
            options={
                'indexes': [models.Index(fields=['district', 'department'], name='dashboards__distric_890b56_idx')],
                'unique_together': {('district', 'department')},
            },
        ),
    ]
