# Generated by Django 6.0.2 on 2026-02-07 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='issue_photos/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='issue_photos/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='issue_photos/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_photo', models.ImageField(blank=True, null=True, upload_to='resolved_photos/')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'officer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_assigned', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(limit_choices_to={'role': 'citizen'}, on_delete=django.db.models.deletion.CASCADE, related_name='issues_reported', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
