# Generated by Django 5.2.4 on 2025-11-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='issue_photos/'),
        ),
        migrations.AddField(
            model_name='issue',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='issue_photos/'),
        ),
        migrations.AddField(
            model_name='issue',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='issue_photos/'),
        ),
    ]
