# Generated by Django 6.0.2 on 2026-02-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_latitude_issue_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='location_source',
            field=models.CharField(choices=[('gps', 'GPS'), ('address', 'Address'), ('manual_city', 'Manual City')], default='manual_city', max_length=20),
        ),
    ]
