# Generated by Django 6.0.2 on 2026-03-19 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_aichat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIChat',
        ),
    ]
