# Generated by Django 6.0.2 on 2026-03-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_delete_aichat'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
    ]
