# Generated by Django 6.0.2 on 2026-03-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_issue_first_response_at_issue_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('pothole', 'Pothole'), ('road_damage', 'Road Damage'), ('water_leakage', 'Water Leakage'), ('street_light', 'Street Light'), ('garbage', 'Garbage'), ('drainage', 'Drainage')], max_length=100),
        ),
    ]
