# Generated by Django 6.0.2 on 2026-03-29 11:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_issue_department_alter_issue_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='district',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='taluka',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='village',
            field=models.CharField(default='parner', max_length=100),
            preserve_default=False,
        ),
    ]
