# Generated by Django 6.0.2 on 2026-04-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0008_issue_district_issue_taluka_issue_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='ward',
            field=models.CharField(db_index=True, default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='department',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
