# Generated by Django 6.0.2 on 2026-04-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0011_issue_status_alignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_at']},
        ),
    ]
