# Generated by Django 6.0.2 on 2026-04-14 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_assignmentlog_options_alter_department_options_and_more'),
        ('issues', '0012_alter_issue_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='accounts.department'),
        ),
    ]
