# Generated by Django 6.0.2 on 2026-04-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0013_alter_issue_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='resolution_image',
            field=models.ImageField(blank=True, null=True, upload_to='resolutions/'),
        ),
    ]
