# Generated by Django 6.0.2 on 2026-04-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0014_issue_resolution_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/'),
        ),
    ]
