# Generated by Django 6.0.2 on 2026-04-19 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0016_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={},
        ),
        migrations.RemoveField(
            model_name='issue',
            name='district',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='proof_image',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='resolution_image',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='resolved_photo',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='taluka',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='village',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='ward',
        ),
        migrations.AddField(
            model_name='issue',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issue',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues_reported', to=settings.AUTH_USER_MODEL),
        ),
    ]
