# Generated by Django 6.0.2 on 2026-04-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0019_issue_status_changed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('resolved', 'Resolved')], db_index=True, default='pending', max_length=20),
        ),
    ]
