# Generated by Django 6.0.2 on 2026-04-21 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_department_alter_user_role'),
        ('issues', '0020_alter_issue_created_at_alter_issue_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['priority', 'status', 'created_at'], name='issues_issu_priorit_1c38d3_idx'),
        ),
    ]
