# Generated by Django 6.0.2 on 2026-04-21 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_department_alter_user_role'),
        ('issues', '0021_issue_resolved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='location_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.location'),
        ),
    ]
