# Generated by Django 6.0.2 on 2026-04-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0022_issue_location_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
