# Generated by Django 6.0.2 on 2026-04-21 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_department_alter_user_role'),
        ('issues', '0023_alter_issue_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='location_fk',
        ),
        migrations.AlterField(
            model_name='issue',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.location'),
        ),
    ]
