# Generated by Django 6.0.2 on 2026-04-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0024_remove_issue_location_fk_alter_issue_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('pothole', 'Pothole'), ('road_damage', 'Road Damage'), ('water_leakage', 'Water Leakage'), ('street_light', 'Street Light'), ('garbage', 'Garbage'), ('drainage', 'Drainage')], max_length=100, unique=True)),
                ('avg_resolution_hours', models.FloatField(default=48.0)),
                ('difficulty_score', models.FloatField(default=1.0)),
                ('total_resolved', models.IntegerField(default=0)),
                ('learning_stability', models.FloatField(default=0.9)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntelligenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('change_type', models.CharField(max_length=50)),
                ('old_value', models.FloatField()),
                ('new_value', models.FloatField()),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='assignment_explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='intelligence_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='issue',
            name='risk_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
