# Generated by Django 6.0.2 on 2026-05-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0025_categoryintelligence_intelligencelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
