# Generated by Django 6.0.2 on 2026-05-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0026_issue_city_issue_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='district',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='taluka',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
