# Generated by Django 6.0.2 on 2026-05-10 13:58

import issues.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0027_alter_issue_city_alter_issue_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='issue_photos/', validators=[issues.validators.validate_secure_image]),
        ),
        migrations.AlterField(
            model_name='issue',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='issue_photos/', validators=[issues.validators.validate_secure_image]),
        ),
        migrations.AlterField(
            model_name='issue',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='issue_photos/', validators=[issues.validators.validate_secure_image]),
        ),
        migrations.AlterField(
            model_name='issue',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/', validators=[issues.validators.validate_secure_image]),
        ),
        migrations.AlterField(
            model_name='issue',
            name='resolution_image',
            field=models.ImageField(blank=True, null=True, upload_to='resolutions/', validators=[issues.validators.validate_secure_image]),
        ),
        migrations.AlterField(
            model_name='issue',
            name='resolved_photo',
            field=models.ImageField(blank=True, null=True, upload_to='resolved_photos/', validators=[issues.validators.validate_secure_image]),
        ),
    ]
