# Generated by Django 5.2.14 on 2026-05-10 14:23

import django.db.models.deletion
import issues.validators
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_department_level_alter_location_name_and_more'),
        ('issues', '0029_alter_issue_priority_escalationappeal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HistoricalIssue',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('pothole', 'Pothole'), ('road_damage', 'Road Damage'), ('water_leakage', 'Water Leakage'), ('street_light', 'Street Light'), ('garbage', 'Garbage'), ('drainage', 'Drainage')], max_length=100)),
                ('priority', models.CharField(choices=[('emergency', 'Emergency (Life/Safety)'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('location_source', models.CharField(choices=[('gps', 'GPS'), ('address', 'Address'), ('manual_city', 'Manual City')], default='manual_city', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('photo1', models.TextField(blank=True, max_length=100, null=True, validators=[issues.validators.validate_secure_image])),
                ('photo2', models.TextField(blank=True, max_length=100, null=True, validators=[issues.validators.validate_secure_image])),
                ('photo3', models.TextField(blank=True, max_length=100, null=True, validators=[issues.validators.validate_secure_image])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('resolved', 'Resolved')], db_index=True, default='pending', max_length=20)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_photo', models.TextField(blank=True, max_length=100, null=True, validators=[issues.validators.validate_secure_image])),
                ('proof_image', models.TextField(blank=True, max_length=100, null=True, validators=[issues.validators.validate_secure_image])),
                ('resolution_image', models.TextField(blank=True, max_length=100, null=True, validators=[issues.validators.validate_secure_image])),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('zone', models.CharField(blank=True, max_length=100, null=True)),
                ('ward', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('village', models.CharField(blank=True, max_length=100, null=True)),
                ('taluka', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('risk_score', models.IntegerField(db_index=True, default=0)),
                ('intelligence_data', models.JSONField(blank=True, default=dict)),
                ('assignment_explanation', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.officer')),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.department')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.location')),
                ('reported_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('status_changed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical issue',
                'verbose_name_plural': 'historical issues',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
