# Generated by Django 5.2.14 on 2026-05-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0030_issue_deleted_at_issue_restored_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalissue',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Prevents duplicate reporting during retries', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Prevents duplicate reporting during retries', max_length=100, null=True, unique=True),
        ),
    ]
