# Generated by Django 5.2.14 on 2026-05-10 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_pendingtask_dispatched_at_pendingtask_status_and_more'),
        ('issues', '0031_historicalissue_idempotency_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField(help_text='Semantic vector for clustering and duplicate detection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='historicalissue',
            name='is_enriched',
            field=models.BooleanField(db_index=True, default=False, help_text='True if geo and risk analysis is complete'),
        ),
        migrations.AddField(
            model_name='issue',
            name='is_enriched',
            field=models.BooleanField(db_index=True, default=False, help_text='True if geo and risk analysis is complete'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['is_enriched', 'created_at'], name='issues_issu_is_enri_e0bc26_idx'),
        ),
        migrations.AddField(
            model_name='issueembedding',
            name='issue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='issues.issue'),
        ),
        migrations.AddIndex(
            model_name='issueembedding',
            index=models.Index(fields=['created_at'], name='issues_issu_created_f736fc_idx'),
        ),
    ]
