# Generated by Django 5.2.14 on 2026-05-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0032_issueembedding_historicalissue_is_enriched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalissue',
            name='sla_multiplier',
            field=models.FloatField(default=1.0, help_text='Denormalized multiplier from environmental conditions'),
        ),
        migrations.AddField(
            model_name='issue',
            name='sla_multiplier',
            field=models.FloatField(default=1.0, help_text='Denormalized multiplier from environmental conditions'),
        ),
    ]
