# Generated by Django 5.2.14 on 2026-05-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0033_historicalissue_sla_multiplier_issue_sla_multiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalissue',
            name='manual_override',
            field=models.BooleanField(default=False, help_text="True if an administrator manually changed the AI's assignment or status"),
        ),
        migrations.AddField(
            model_name='issue',
            name='manual_override',
            field=models.BooleanField(default=False, help_text="True if an administrator manually changed the AI's assignment or status"),
        ),
    ]
