# Generated by Django 5.2.14 on 2026-05-12 16:10

import django.db.models.deletion
import issues.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0034_historicalissue_manual_override_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueAIContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.IntegerField(db_index=True, default=0)),
                ('intelligence_data', models.JSONField(blank=True, default=dict)),
                ('assignment_explanation', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_enriched', models.BooleanField(db_index=True, default=False)),
                ('sla_multiplier', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='IssueEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Issue Created'), ('assigned', 'Officer Assigned'), ('escalated', 'Issue Escalated'), ('resolved', 'Issue Resolved'), ('status_changed', 'Status Changed'), ('priority_changed', 'Priority Changed'), ('metadata_updated', 'Metadata Updated'), ('officer_overloaded', 'Officer Overloaded')], db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sequence_number', models.PositiveIntegerField(db_index=True, help_text='Monotonic order per issue')),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('causation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.IntegerField(default=1)),
                ('payload', models.JSONField(default=dict, help_text='Delta of changes or specific event context')),
            ],
            options={
                'ordering': ['issue', 'sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='IssueMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='issue_photos/', validators=[issues.validators.validate_secure_image])),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='issue_photos/', validators=[issues.validators.validate_secure_image])),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='issue_photos/', validators=[issues.validators.validate_secure_image])),
                ('resolved_photo', models.ImageField(blank=True, null=True, upload_to='resolved_photos/', validators=[issues.validators.validate_secure_image])),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='proofs/', validators=[issues.validators.validate_secure_image])),
                ('resolution_image', models.ImageField(blank=True, null=True, upload_to='resolutions/', validators=[issues.validators.validate_secure_image])),
            ],
        ),
        migrations.CreateModel(
            name='ProjectionCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projection_name', models.CharField(max_length=100, unique=True)),
                ('last_event_id', models.IntegerField(default=0)),
                ('last_processed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalissue',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='historicalissue',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='historicalissue',
            name='department',
        ),
        migrations.RemoveField(
            model_name='historicalissue',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalissue',
            name='location',
        ),
        migrations.RemoveField(
            model_name='historicalissue',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='historicalissue',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='historicalissue',
            name='status_changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalissue',
            name='updated_by',
        ),
        migrations.RemoveIndex(
            model_name='issue',
            name='issues_issu_is_enri_e0bc26_idx',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='assignment_explanation',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='description',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='idempotency_key',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='intelligence_data',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='is_enriched',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='proof_image',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='resolution_image',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='resolved_photo',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='risk_score',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='sla_multiplier',
        ),
        migrations.AddField(
            model_name='issueaicontext',
            name='issue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_context', to='issues.issue'),
        ),
        migrations.AddField(
            model_name='issueevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issueevent',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_events', to='issues.issue'),
        ),
        migrations.AddField(
            model_name='issuemetadata',
            name='issue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='issues.issue'),
        ),
        migrations.DeleteModel(
            name='HistoricalIssue',
        ),
        migrations.AddIndex(
            model_name='issueevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='issues_issu_event_t_8db2d3_idx'),
        ),
        migrations.AddIndex(
            model_name='issueevent',
            index=models.Index(fields=['correlation_id'], name='issues_issu_correla_d33829_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='issueevent',
            unique_together={('issue', 'sequence_number')},
        ),
    ]
