# Generated by Django 5.2.14 on 2026-05-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0035_issueaicontext_issueevent_issuemetadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='governance_scope',
            field=models.CharField(choices=[('village', 'Village'), ('ward', 'Ward'), ('taluka', 'Taluka'), ('city', 'City'), ('district', 'District')], db_index=True, default='village', max_length=20),
        ),
    ]
