# Generated by Django 5.2.14 on 2026-05-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0036_issue_governance_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryintelligence',
            name='category',
            field=models.CharField(choices=[('pwd', 'Public Works Department (PWD)'), ('water_supply', 'Water Supply Department'), ('sanitation', 'Sanitation Department'), ('electricity', 'Electricity Department'), ('road_transport', 'Road & Transport Department'), ('drainage_sewerage', 'Drainage & Sewerage Department'), ('health', 'Health Department'), ('environment', 'Environment Department'), ('urban_planning', 'Urban Planning Department'), ('disaster_management', 'Disaster Management Department'), ('traffic_police', 'Traffic Police Department'), ('municipal_engineering', 'Municipal Engineering Department'), ('pothole', 'Public Works Department (PWD) [Legacy]'), ('road_damage', 'Public Works Department (PWD) [Legacy]'), ('water_leakage', 'Water Supply Department [Legacy]'), ('street_light', 'Electricity Department [Legacy]'), ('garbage', 'Sanitation Department [Legacy]'), ('drainage', 'Drainage & Sewerage Department [Legacy]')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('pwd', 'Public Works Department (PWD)'), ('water_supply', 'Water Supply Department'), ('sanitation', 'Sanitation Department'), ('electricity', 'Electricity Department'), ('road_transport', 'Road & Transport Department'), ('drainage_sewerage', 'Drainage & Sewerage Department'), ('health', 'Health Department'), ('environment', 'Environment Department'), ('urban_planning', 'Urban Planning Department'), ('disaster_management', 'Disaster Management Department'), ('traffic_police', 'Traffic Police Department'), ('municipal_engineering', 'Municipal Engineering Department'), ('pothole', 'Public Works Department (PWD) [Legacy]'), ('road_damage', 'Public Works Department (PWD) [Legacy]'), ('water_leakage', 'Water Supply Department [Legacy]'), ('street_light', 'Electricity Department [Legacy]'), ('garbage', 'Sanitation Department [Legacy]'), ('drainage', 'Drainage & Sewerage Department [Legacy]')], max_length=100),
        ),
    ]
