# Generated by Django 6.0.2 on 2026-04-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_issues', models.IntegerField(default=0)),
                ('resolved', models.IntegerField(default=0)),
                ('in_progress', models.IntegerField(default=0)),
                ('pending', models.IntegerField(default=0)),
            ],
        ),
    ]
