# Generated by Django 6.0.2 on 2026-04-14 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
