# Generated by Django 6.0.2 on 2026-04-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_assignmentlog_issueimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='district',
            field=models.CharField(default='m', max_length=100),
            preserve_default=False,
        ),
    ]
