# Generated by Django 6.0.2 on 2026-04-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_officer_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='taluka',
            field=models.CharField(default='padali', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officer',
            name='village',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
