# Generated by Django 6.0.2 on 2026-04-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_officer_taluka_officer_village'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='level',
            field=models.CharField(choices=[('village', 'Village'), ('taluka', 'Taluka'), ('district', 'District')], default='village', max_length=20),
        ),
    ]
