# Generated by Django 6.0.2 on 2026-04-12 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_managers'),
        ('issues', '0012_alter_issue_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentlog',
            options={'ordering': ['-assigned_at']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['type', 'name']},
        ),
        migrations.AlterModelOptions(
            name='officer',
            options={'ordering': ['user__username']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.AlterField(
            model_name='assignmentlog',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_logs', to='issues.issue'),
        ),
        migrations.AlterField(
            model_name='assignmentlog',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_logs', to='accounts.officer'),
        ),
        migrations.AlterField(
            model_name='issueimage',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='issues.issue'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='officer',
            name='taluka',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='officer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='officer',
            name='village',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
