# Generated by Django 6.0.2 on 2026-04-19 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_assignmentlog_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('officer', 'Officer'), ('dept_admin', 'Department Admin'), ('super_admin', 'Super Admin')], db_index=True, default='citizen', max_length=20),
        ),
    ]
