# Generated by Django 6.0.2 on 2026-05-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_officer_address_officer_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='officer',
            name='ward',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='level',
            field=models.CharField(choices=[('village', 'Village'), ('taluka', 'Taluka'), ('district', 'District'), ('city', 'City'), ('zone', 'Zone'), ('ward', 'Ward')], default='village', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('village', 'Village'), ('taluka', 'Taluka'), ('district', 'District'), ('city', 'City'), ('zone', 'Zone'), ('ward', 'Ward')], max_length=20),
        ),
        migrations.AlterField(
            model_name='officer',
            name='level',
            field=models.CharField(choices=[('village', 'Village'), ('taluka', 'Taluka'), ('district', 'District'), ('city', 'City'), ('zone', 'Zone'), ('ward', 'Ward')], max_length=20),
        ),
    ]
