# Generated by Django 6.0.2 on 2026-05-10 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_normalize_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffingPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('village', 'Village'), ('taluka', 'Taluka'), ('district', 'District'), ('city', 'City'), ('zone', 'Zone'), ('ward', 'Ward')], max_length=20)),
                ('is_rural', models.BooleanField(default=True, help_text='True for Rural (Village/Taluka), False for Urban (City/Zone/Ward)')),
                ('ratio', models.IntegerField(default=0, help_text='1 officer per X villages (for rural village-level roles)')),
                ('fixed_count', models.IntegerField(default=0, help_text='Fixed officers per unit (e.g., 1 per Ward, 1 per Zone)')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='accounts.department')),
            ],
            options={
                'verbose_name_plural': 'Staffing Policies',
                'unique_together': {('department', 'level', 'is_rural')},
            },
        ),
    ]
