# Generated by Django 6.0.2 on 2026-05-10 13:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_staffingpolicy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffingpolicy',
            options={'ordering': ['-version', 'department'], 'verbose_name_plural': 'Staffing Policies'},
        ),
        migrations.AlterUniqueTogether(
            name='staffingpolicy',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='staffingpolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffingpolicy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffingpolicy',
            name='effective_from',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffingpolicy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staffingpolicy',
            name='target_district',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'district'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_policies', to='accounts.location'),
        ),
        migrations.AddField(
            model_name='staffingpolicy',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='staffingpolicy',
            unique_together={('department', 'level', 'is_rural', 'target_district', 'version')},
        ),
        migrations.CreateModel(
            name='StaffingRollout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft (Simulation)'), ('approved', 'Approved for Rollout'), ('completed', 'Rollout Completed'), ('failed', 'Rollout Failed')], default='draft', max_length=20)),
                ('policy_snapshot', models.JSONField(default=dict, help_text='Snapshot of active policies at time of simulation')),
                ('estimated_officers', models.IntegerField(default=0)),
                ('actual_officers_created', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rollouts', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(limit_choices_to={'type': 'district'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
