# Generated by Django 6.0.2 on 2026-05-10 13:58

import issues.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_staffingpolicy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueimage',
            name='image',
            field=models.ImageField(upload_to='issues/', validators=[issues.validators.validate_secure_image]),
        ),
    ]
