# Generated by Django 6.0.2 on 2026-05-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='level',
            field=models.CharField(choices=[('village', 'Village'), ('taluka', 'Taluka'), ('district', 'District'), ('city', 'City'), ('zone', 'Zone'), ('ward', 'Ward')], db_index=True, default='village', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('village', 'Village'), ('taluka', 'Taluka'), ('district', 'District'), ('city', 'City'), ('zone', 'Zone'), ('ward', 'Ward')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='officer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='level',
            field=models.CharField(choices=[('village', 'Village'), ('taluka', 'Taluka'), ('district', 'District'), ('city', 'City'), ('zone', 'Zone'), ('ward', 'Ward')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='officer',
            index=models.Index(fields=['location', 'department', 'level'], name='accounts_of_locatio_eb6a78_idx'),
        ),
        migrations.AddIndex(
            model_name='officer',
            index=models.Index(fields=['district', 'taluka', 'village'], name='accounts_of_distric_4d6970_idx'),
        ),
        migrations.AddIndex(
            model_name='officer',
            index=models.Index(fields=['city', 'zone', 'ward'], name='accounts_of_city_235649_idx'),
        ),
    ]
