# Generated by Django 5.2.14 on 2026-05-10 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_department_level_alter_location_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('leave', 'Planned Leave'), ('sick', 'Sickness'), ('emergency', 'Family Emergency'), ('training', 'Government Training'), ('transfer', 'In-Transit (Transfer)')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='officer',
            name='active_assigned_count',
            field=models.IntegerField(default=0, help_text='Denormalized count of current non-resolved issues'),
        ),
        migrations.AddField(
            model_name='officer',
            name='burnout_risk',
            field=models.FloatField(default=0.0, help_text='Probability of delayed response based on current pressure'),
        ),
        migrations.AddField(
            model_name='officer',
            name='fatigue_level',
            field=models.IntegerField(default=0, help_text='0-100: Impacted by workload and duration of active duty'),
        ),
        migrations.AddField(
            model_name='officer',
            name='last_active_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='reliability_score',
            field=models.IntegerField(default=100, help_text='0-100: Degrades with missed SLAs and reassignment disputes'),
        ),
        migrations.AddIndex(
            model_name='officer',
            index=models.Index(fields=['fatigue_level', 'is_active'], name='accounts_of_fatigue_1a46b4_idx'),
        ),
        migrations.AddField(
            model_name='officerabsence',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='accounts.officer'),
        ),
        migrations.AddField(
            model_name='officerabsence',
            name='substitute_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitutions', to='accounts.officer'),
        ),
    ]
