# Generated by Django 5.2.14 on 2026-05-10 14:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_officerabsence_officer_active_assigned_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeDirective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('vip', 'VIP/Collector Priority'), ('district_emergency', 'District-Wide Emergency'), ('policy_bypass', 'Staffing Policy Bypass'), ('legal', 'Legal/Court Directive')], max_length=50)),
                ('authority_reference', models.CharField(help_text='Order number, Collector ID, or MLA reference', max_length=200)),
                ('justification', models.TextField()),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(limit_choices_to={'type': 'district'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
