# Generated by Django 5.2.14 on 2026-05-10 14:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_administrativedirective'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictOperationalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('monsoon', 'Active Monsoon'), ('heatwave', 'Extreme Heatwave'), ('strike', 'Administrative Strike'), ('holiday', 'Public Holiday Period'), ('crisis', 'Active Crisis/Emergency')], max_length=20)),
                ('sla_multiplier', models.FloatField(default=1.5, help_text='Multiplies SLA days (e.g. 1.5 = 50% delay allowed)')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('district', models.ForeignKey(limit_choices_to={'type': 'district'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.location')),
            ],
        ),
    ]
