# Generated by Django 5.2.14 on 2026-05-10 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_districtoperationalcondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativedirective',
            name='authority_reference',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='districtoperationalcondition',
            name='sla_multiplier',
            field=models.FloatField(default=1.5),
        ),
        migrations.AlterField(
            model_name='officer',
            name='active_assigned_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CitizenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust_score', models.IntegerField(default=50)),
                ('report_quality_avg', models.FloatField(default=0.5)),
                ('frustration_index', models.FloatField(default=0.0)),
                ('total_reports', models.IntegerField(default=0)),
                ('valid_reports', models.IntegerField(default=0)),
                ('last_reported_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
