# Generated by Django 5.2.14 on 2026-05-10 14:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_administrativedirective_authority_reference_and_more'),
        ('issues', '0030_issue_deleted_at_issue_restored_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('flood', 'Severe Flooding'), ('landslide', 'Landslide/Collapse'), ('epidemic', 'Disease Outbreak'), ('fire', 'Major Urban Fire'), ('civil', 'Civil Unrest')], max_length=20)),
                ('is_declared', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('district', models.ForeignKey(limit_choices_to={'type': 'district'}, on_delete=django.db.models.deletion.CASCADE, to='accounts.location')),
                ('emergency_command_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='command_center_disasters', to='accounts.officer')),
            ],
        ),
        migrations.CreateModel(
            name='JurisdictionDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Dispute Raised'), ('arbitration', 'In Arbitration'), ('resolved', 'Responsibility Fixed'), ('rejected', 'Dispute Dismissed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('arbitrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_decisions', to=settings.AUTH_USER_MODEL)),
                ('disputing_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_filed', to='accounts.officer')),
                ('final_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_resolutions', to='accounts.department')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='issues.issue')),
                ('original_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_raised', to='accounts.department')),
            ],
        ),
        migrations.CreateModel(
            name='SystemFailureEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('network', 'Regional Network Outage'), ('power', 'Localized Power Failure'), ('congestion', 'Queue/Notification Congestion'), ('maintenance', 'Emergency System Maintenance')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('impact_factor', models.FloatField(default=2.0)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('district', models.ForeignKey(blank=True, limit_choices_to={'type': 'district'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.location')),
            ],
        ),
    ]
