# Generated by Django 5.2.14 on 2026-05-10 14:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_disasterevent_jurisdictiondispute_systemfailureevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={},
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='details',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='resource_id',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='resource_type',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user_agent',
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('p0', 'CRITICAL - System Down'), ('p1', 'HIGH - Major Degraded'), ('p2', 'MEDIUM - Partial Issues'), ('p3', 'LOW - Minor/Normal')], default='p2', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Investigating'), ('mitigated', 'Mitigated'), ('resolved', 'Resolved (Postmortem Pending)'), ('closed', 'Closed (Postmortem Complete)')], default='open', max_length=20)),
                ('incident_type', models.CharField(help_text='e.g. REDIS_DOWN, QUEUE_CONGESTION', max_length=100)),
                ('description', models.TextField()),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mitigated_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('postmortem', models.TextField(blank=True)),
                ('reproduction_steps', models.TextField(blank=True)),
                ('impacted_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.location')),
            ],
        ),
        migrations.CreateModel(
            name='OperationalMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'timestamp'], name='accounts_op_name_0414f2_idx')],
            },
        ),
    ]
