# Generated by Django 5.2.14 on 2026-05-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_pendingtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingtask',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendingtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Dispatch'), ('dispatched', 'Dispatched to Broker'), ('failed', 'Permanent Failure')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='pendingtask',
            index=models.Index(fields=['status', 'created_at'], name='accounts_pe_status_e30948_idx'),
        ),
    ]
