# Generated by Django 5.2.14 on 2026-05-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_pendingtask_dispatched_at_pendingtask_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('avg_readiness', models.FloatField(default=0.0)),
                ('total_staff', models.IntegerField(default=0)),
                ('pending_issues', models.IntegerField(default=0)),
                ('pressure_index', models.FloatField(default=0.0)),
                ('outbox_backlog', models.IntegerField(default=0)),
                ('failed_tasks', models.IntegerField(default=0)),
                ('system_latency_ms', models.FloatField(default=0.0)),
                ('avg_ai_confidence', models.FloatField(default=0.0)),
                ('calibration_drift', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='accounts_he_timesta_51fb19_idx')],
            },
        ),
    ]
