# Generated by Django 5.2.14 on 2026-05-11 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_healthsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='administrative_audit_linkage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='alternate_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='disaster_response_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='duty_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='emergency_response_eligibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officer',
            name='escalation_authority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officer',
            name='escalation_reachability',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='field_vs_desk',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='geo_assignment_integrity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='jurisdiction_scope',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='multilingual_capability',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='office_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='office_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='official_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='reporting_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='accounts.officer'),
        ),
        migrations.AddField(
            model_name='officer',
            name='response_priority_level',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='officer',
            name='service_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='shift_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='verification_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='verified_communication_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='officer',
            name='workload_capacity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='officer',
            name='workload_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
