# Generated by Django 5.2.14 on 2026-05-12 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_officer_administrative_audit_linkage_and_more'),
        ('issues', '0034_historicalissue_manual_override_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('phone_no', models.CharField(blank=True, max_length=15)),
                ('authority_level', models.IntegerField(default=1)),
                ('override_permissions', models.JSONField(blank=True, default=dict)),
                ('jurisdiction_scope', models.CharField(blank=True, max_length=100)),
                ('emergency_privileges', models.BooleanField(default=False)),
                ('audit_privileges', models.BooleanField(default=False)),
                ('governance_control_metadata', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.RenameModel(
            old_name='Officer',
            new_name='OfficerProfile',
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, db_column='address', max_length=200),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='_legacy_address',
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, db_column='city', max_length=100),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='city',
            new_name='_legacy_city',
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(db_column='full_name', max_length=150),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='_legacy_full_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, db_column='latitude', decimal_places=6, max_digits=9, null=True),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='latitude',
            new_name='_legacy_latitude',
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, db_column='longitude', decimal_places=6, max_digits=9, null=True),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='longitude',
            new_name='_legacy_longitude',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(blank=True, db_column='phone_no', max_length=15),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='phone_no',
            new_name='_legacy_phone_no',
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, db_column='state', max_length=100),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='state',
            new_name='_legacy_state',
        ),
        migrations.RenameIndex(
            model_name='officerprofile',
            new_name='accounts_of_locatio_055dcb_idx',
            old_name='accounts_of_locatio_eb6a78_idx',
        ),
        migrations.RenameIndex(
            model_name='officerprofile',
            new_name='accounts_of_distric_8a39f6_idx',
            old_name='accounts_of_distric_4d6970_idx',
        ),
        migrations.RenameIndex(
            model_name='officerprofile',
            new_name='accounts_of_city_f03ce1_idx',
            old_name='accounts_of_city_235649_idx',
        ),
        migrations.RenameIndex(
            model_name='officerprofile',
            new_name='accounts_of_fatigue_9c0d63_idx',
            old_name='accounts_of_fatigue_1a46b4_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_admins', to='accounts.department'),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='department',
            new_name='_legacy_department',
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='accessibility_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='demographic_safe_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='preferred_language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='reporting_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('officer', 'OfficerProfile'), ('dept_admin', 'Department Admin'), ('super_admin', 'Super Admin')], db_index=True, default='citizen', max_length=20),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_profiles', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
