# Generated by Django 5.2.14 on 2026-05-13 15:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_adminprofile_rename_officer_officerprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenprofile',
            name='aadhaar_last4',
            field=models.CharField(blank=True, max_length=4, verbose_name='Aadhaar (Last 4)'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='alternate_phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Alternate Phone Number'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='citizen_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('banned', 'Banned'), ('pending', 'Pending Verification')], default='active', max_length=20, verbose_name='Citizen Status'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='disability_status',
            field=models.BooleanField(default=False, verbose_name='Disability Status'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='district',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='education',
            field=models.CharField(blank=True, max_length=100, verbose_name='Education'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Emergency Contact Name'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Emergency Contact Number'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='family_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Family Size'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('not_specified', 'Prefer not to say')], default='not_specified', max_length=20, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='income_range',
            field=models.CharField(blank=True, max_length=50, verbose_name='Income Range'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='landmark',
            field=models.CharField(blank=True, max_length=100, verbose_name='Landmark'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Middle Name'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Occupation'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=15, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, verbose_name='Pincode'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='citizen_profiles/', verbose_name='Profile Photo'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='rejected_reports',
            field=models.IntegerField(default=0, verbose_name='Rejected Reports'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='spam_reports',
            field=models.IntegerField(default=0, verbose_name='Spam Reports'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='special_assistance_required',
            field=models.TextField(blank=True, verbose_name='Special Assistance Required'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='taluka',
            field=models.CharField(blank=True, max_length=100, verbose_name='Taluka'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Verification Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='unverified', max_length=20, verbose_name='Verification Status'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='village',
            field=models.CharField(blank=True, max_length=100, verbose_name='Village'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='voter_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Voter ID'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='ward',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ward'),
        ),
        migrations.AlterField(
            model_name='citizenprofile',
            name='accessibility_settings',
            field=models.JSONField(blank=True, default=dict, verbose_name='Accessibility Settings'),
        ),
        migrations.AlterField(
            model_name='citizenprofile',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='citizenprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='citizenprofile',
            name='last_reported_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Reported At'),
        ),
        migrations.AlterField(
            model_name='citizenprofile',
            name='preferred_language',
            field=models.CharField(blank=True, max_length=50, verbose_name='Preferred Language'),
        ),
        migrations.AlterField(
            model_name='citizenprofile',
            name='reporting_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Reporting Metadata'),
        ),
        migrations.AlterField(
            model_name='citizenprofile',
            name='total_reports',
            field=models.IntegerField(default=0, verbose_name='Total Reports'),
        ),
        migrations.AlterField(
            model_name='citizenprofile',
            name='trust_score',
            field=models.IntegerField(db_index=True, default=50, verbose_name='Trust Score'),
        ),
        migrations.AlterField(
            model_name='citizenprofile',
            name='valid_reports',
            field=models.IntegerField(default=0, verbose_name='Valid Reports'),
        ),
    ]
