# Generated by Django 5.2.14 on 2026-05-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_citizenprofile_aadhaar_last4_citizenprofile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='citizenprofile',
            name='demographic_safe_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Demographic Safe Metadata'),
        ),
    ]
