# Generated by Django 6.0.2 on 2026-04-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_aiactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiactionlog',
            name='action_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='aiactionlog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiactionlog',
            name='execution_result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aiactionlog',
            name='request_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aiactionlog',
            name='validated_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
