# Generated by Django 6.0.2 on 2026-04-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_aiactionlog_action_token_aiactionlog_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiactionlog',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='aiactionlog',
            name='session_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
