# Generated by Django 6.0.2 on 2026-04-30 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0025_categoryintelligence_intelligencelog_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('issue_created', 'Issue Created'), ('issue_assigned', 'Issue Assigned'), ('issue_updated', 'Issue Updated'), ('issue_resolved', 'Issue Resolved'), ('profile_updated', 'Profile Updated')], default='issue_updated', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues.issue'),
        ),
    ]
