# Generated by Django 6.0.2 on 2026-04-30 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notification_type',
            new_name='type',
        ),
    ]
