# Generated by Django 5.2.14 on 2026-05-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_notification_type_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS')], default='in_app', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivery_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='error_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('issue_created', 'Issue Created'), ('issue_assigned', 'Issue Assigned'), ('issue_updated', 'Issue Updated'), ('issue_resolved', 'Issue Resolved'), ('profile_updated', 'Profile Updated'), ('escalation', 'Escalation')], default='issue_updated', max_length=20),
        ),
    ]
