# Generated by Django 5.2.14 on 2026-05-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_channel_notification_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Prevents duplicate notifications', max_length=150, null=True, unique=True),
        ),
    ]
