# Generated by Django 5.2.14 on 2026-05-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical (Immediate Action)'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, default='medium', max_length=10),
        ),
    ]
